---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: _default

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.4
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[hollandbackup::default]
      - recipe[hollandbackup::mysqldump]
      - recipe[hollandbackup::main]
      - recipe[hollandbackup::backupsets]
    attributes: