AlignParameters:
  Enabled: false

FileName:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

RedundantBegin:
  Enabled: false

UselessAssignment:
  Enabled: false

MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - '.kitchen/*'
